### PR TITLE
Ansible repo - Allow actions to create PRs

### PR DESCRIPTION
**Pull request by ygalblum**
The release action creates a PR updating the changelog

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by netomi** [comment]
The reason no change is displayed in the diff view is because you try to set a setting on a repo level, that is not permitted on org level:

image

So when trying to set this property on the web ui it is also grayed out:

image

We chose not to display info validation messages, but in this case it probably should be a warning that is always displayed. If you want to enable that setting in any way, you also have to enable it on org level.

**Comment by ygalblum** [comment]
@netomi Does this mean that I have to also enable it at the organization level? Is that OK?
BTW where is the picture you've attached from?

**Comment by netomi** [comment]
Its ok to enable it on org level, otherwise it can not be set on repo level. In our defaults we have it set to true anyways as in general it should be fine to use that feature.

The screenshot comes from running the otterdog cli tool. the same functionality will be available soon in your PRs, where you can then use a comment like `/validate info` to see all validation info messages.

**Comment by ygalblum** [comment]
@netomi I've updated my change to enable it also at the org level

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live.

**Comment by ygalblum** [comment]
> changes are live.

Thanks

**Pull request merged**
